---
language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
    - PUPPET_GEM_VERSION="~> 3.5.1"
    - PUPPET_GEM_VERSION="~> 3.6.0"
    - PUPPET_GEM_VERSION="~> 3.7.0"

sudo: false

bundler_args: --without system_tests
script: 'bundle exec rake validate && bundle exec rake lint && SPEC_OPTS="--format documentation" bundle exec rake spec'

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.1.0"

notifications:
  email: false

